Readd scriplets to make it work the unbundle of expat and zilb
fix errors like :

```
g++ -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -c -DLIBSKINDESIGNERAPIVERSION='"0.1.2"' -DPLUGIN_NAME_I18N='"plex"' -DPLUGIN='"plex"' -D_GNU_SOURCE -DSKINDESIGNER   -o plex.o plex.cpp
In file included from /usr/include/Poco/SAX/SAXParser.h:23,
                 from /usr/include/Poco/DOM/DOMParser.h:22,
                 from user.h:4,
                 from Plexservice.h:33,
                 from plex.h:14,
                 from PlexHTTPRequestHandler.h:14,
                 from ControlServer.h:10,
                 from plex.cpp:1:
/usr/include/Poco/XML/ParserEngine.h:24:10: fatal error: Poco/XML/expat.h: No such file or directory
   24 | #include "Poco/XML/expat.h"
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
```